[build-system]
requires = [
    "wheel",
    "setuptools>=45",
    "setuptools_scm[toml]>=6.0",
    "pytest>=6.0",
    "torch>=1.12.0",
    "pybind11>=2.10.0"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3